SELECT DISTINCT
    PFAC.PEFAPECS||'- '||CL.CICLDESC PERIODO_CONSUMO,
    CL.CICLDESC CICLO_FACTURA,
    PFAC.PEFACODI ID_PERIODO,
    PFAC.PEFADESC PERIODO,
    CONS.CICOCODI||'-('||CONS.CICODESC ||')' CICLO_CONSUMO,
    SER.SESUSUSC CUENTA,
    SER.SESUNUSE PRODUCTO,
    GSUB.SUBSCRIBER_NAME NOMBRES,
    GSUT.SUBSCRIBER_TYPE_ID||'-'||GSUT.DESCRIPTION TIPO_CLIENTE,
    PSUS.PLSUCODI ||'-'||PSUS.PLSUDESC PLAN_FACTURACION,
            (select description
            from SFBZ0800.compsesu a, SFBZ0800.servsusc se, SFBZ0800.ps_class_service c
            where a.cmsssesu=SER.sesunuse
            and se.sesususc=SER.sesususc
            and c.class_service_id = a.cmssclse
            and a.cmsstcom = 58
            and a.cmssfere>sysdate
            and rownum = 1) ALTERNATIVA,
    '' ANALISIS_CONSUMO,
    SERVI.SERVCODI||'-'||SERVI.SERVDESC SERVICIO,
    --TCONS.TCONCODI||'-'||TCONS.TCONDESC TIPO_CONSUMO
    CAT.CATECODI ||'-'||CAT.CATEDESC CATEGORIA,
    SUB.SUCACODI||'-'||SUB.SUCADESC SUBCATEGORIA,
    AB.ADDRESS DIRECCION,
    (SELECT ABS.PREMISE_STATUS_ID||'-'||ABS.DESCRIPTION FROM SFBZ0800.AB_PREMISE_STATUS ABS,
    SFBZ0800.AB_PREMISE ABP WHERE ABS.PREMISE_STATUS_ID=ABP.PREMISE_STATUS_ID AND ABP.PREMISE_ID = AB.ESTATE_NUMBER) ESTADO_PREDIO,
    ELME.EMSSCOEM NUMERO_ELEMENTO,
    ELME.EMSSFEIN INSTALADO_EL,
    '' UNIDADES1,
    '' UNIDADES2,
    (Select cavcdesc from SFBZ0800.calivaco
      Where cavccodi = CONSE.cosscavc 
        and rownum=1) CALIFICACION,
    '' FUNCION_CALCULO,
    NVL((SELECT OBS.OBLECODI||'-'||OBS.OBLEDESC FROM SFBZ0800.OBSELECT OBS WHERE LEC.LEEMOBLE=OBS.OBLECODI ),'NO-VALIDO')OBSERVACION_1,
    '' ID
FROM 
    SFBZ0800.SERVSUSC SER,
    SFBZ0800.CONSSESU conse,
    SFBZ0800.SERVICIO SERVI,
    SFBZ0800.PR_PRODUCT PR,
    SFBZ0800.AB_ADDRESS AB,
    SFBZ0800.elmesesu ELME,
    SFBZ0800.ELEMMEDI ELEM,
    SFBZ0800.GE_SUBSCRIBER GSUB,
    SFBZ0800.GE_SUBSCRIBER_TYPE GSUT,
    SFBZ0800.TIPOCONS TCONS,
    SFBZ0800.CICLO CL,
    SFBZ0800.CICLCONS CONS,
    SFBZ0800.PERIFACT PFAC,
    SFBZ0800.PLANSUSC PSUS,
    SFBZ0800.CATEGORI CAT,
    SFBZ0800.SUBCATEG SUB,
    SFBZ0800.LECTELME LEC
WHERE 
    SESUCICL=CICLCODI
    AND PR.PRODUCT_ID=SER.SESUNUSE
    AND PR.ADDRESS_ID = AB.ADDRESS_ID
    AND SERVI.SERVCODI=PR.product_type_id
    AND GSUB.SUBSCRIBER_ID=SER.SESUSUSC
    AND GSUB.SUBSCRIBER_TYPE_ID=GSUT.SUBSCRIBER_TYPE_ID
    AND conse.COSSTCON=TCONS.TCONCODI
    AND ELME.EMSSSESU=SER.SESUNUSE
    AND ELME.EMSSSERV=SERVI.SERVCODI
    AND LEC.LEEMPEFA=PFAC.PEFACODI
    AND LEC.LEEMSESU=SER.SESUNUSE
    AND ELME.EMSSELME=ELEM.ELMEIDEM
    --AND conse.COSSSESU=PR.PRODUCT_ID
    AND SER.SESUNUSE=CONSE.COSSSESU 
    AND CONSE.COSSPEFA=PFAC.PEFACODI
    AND CAT.CATECODI=SER.SESUCATE
    AND SUB.SUCACATE=SER.SESUCATE
    AND SUB.SUCACODI=SER.SESUSUCA
    AND PSUS.PLSUCODI=SER.SESUPLFA
    AND PFAC.PEFACICL=CL.CICLCODI
    AND SER.SESUCICL=PFAC.PEFACICL
    AND CL.CICLCICO=CONS.CICOCODI
    AND PFAC.PEFACODI =45818 --- 50168
    AND SER.SESUNUSE  = 1000022311;/